// <auto-generated />
using Algebra.HelloWorld.Web.MvcApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Algebra.HelloWorld.Web.MvcApp.Migrations
{
    [DbContext(typeof(PetShopDbContext))]
    [Migration("20241010190156_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Algebra.HelloWorld.Web.MvcApp.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PetShopId")
                        .HasColumnType("int");

                    b.Property<int>("PetTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PetShopId");

                    b.HasIndex("PetTypeId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Algebra.HelloWorld.Web.MvcApp.Models.PetShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Address")
                        .IsUnique();

                    b.ToTable("PetShops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Zagreb",
                            Name = "ASPets"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Varaždin",
                            Name = "ASPets"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Pula",
                            Name = "ASPets"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Osijek",
                            Name = "ASPets"
                        });
                });

            modelBuilder.Entity("Algebra.HelloWorld.Web.MvcApp.Models.PetType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mačka"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kornjača"
                        });
                });

            modelBuilder.Entity("Algebra.HelloWorld.Web.MvcApp.Models.Pet", b =>
                {
                    b.HasOne("Algebra.HelloWorld.Web.MvcApp.Models.PetShop", "PetShop")
                        .WithMany("Pets")
                        .HasForeignKey("PetShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Algebra.HelloWorld.Web.MvcApp.Models.PetType", "PetType")
                        .WithMany()
                        .HasForeignKey("PetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetShop");

                    b.Navigation("PetType");
                });

            modelBuilder.Entity("Algebra.HelloWorld.Web.MvcApp.Models.PetShop", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
